package aspects;

import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.AfterThrowing;

import exceptions.NetworkException;

public class RetryAspect {
	
	@AfterThrowing(pointcut = "execution(* *.*(..))",throwing = "e")
	public void autoRetryNetwork(JoinPoint joinPoint, NetworkException e)
	{
		System.out.println("An exception : "+e+ " has been thrown");
	}

}
